#!/usr/bin/env bash
# Render and push the Homebrew cask for one released member.
# Usage: publish-cask.sh <member>  (run from the member directory; expects
# dist/ from goreleaser, TAG, VERSION, GH_TOKEN, BOT_NAME, BOT_EMAIL.)

set -euo pipefail

member=${1:?member name required}
case "$member" in
  slopguard) depends_stanza='  depends_on formula: [
      "git",
      "trufflehog",
    ]
' ;;
  *) depends_stanza='' ;;
esac
[[ "${VERSION:-}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "VERSION missing or invalid" >&2; exit 1; }
[[ "${TAG:-}" == "$member/$VERSION" ]] || { echo "TAG must be $member/VERSION" >&2; exit 1; }

# A retry after publish has no dist/; the published release is the source.
if [ ! -f dist/checksums.txt ]; then
  mkdir -p dist
  gh release download "$TAG" --repo uinaf/ffsstack -p checksums.txt -D dist
fi

sum() {
  awk -v f="${member}_${VERSION}_$1.tar.gz" '$2 == f { print $1 }' dist/checksums.txt
}
darwin_amd64=$(sum darwin_amd64); darwin_arm64=$(sum darwin_arm64)
linux_amd64=$(sum linux_amd64); linux_arm64=$(sum linux_arm64)
for checksum in "$darwin_amd64" "$darwin_arm64" "$linux_amd64" "$linux_arm64"; do
  [[ "$checksum" =~ ^[0-9a-f]{64}$ ]] || { echo "missing archive checksum" >&2; exit 1; }
done

# Release-download URLs URL-encode the slash in the member-prefixed tag.
base="https://github.com/uinaf/ffsstack/releases/download/${member}%2F${VERSION}"
case "$member" in
  slopmachine) description="Deterministic and structured approach to slop cannoning" ;;
  slopguard) description="Structured independent code review as a CLI and agent skill" ;;
  *) description="$member" ;;
esac

tap_dir=$(mktemp -d)
trap 'rm -rf "$tap_dir"' EXIT
git clone --depth 1 "https://x-access-token:${GH_TOKEN}@github.com/uinaf/homebrew-tap.git" "$tap_dir"

# Rerunning an old workflow must never downgrade the tap.
existing=$(sed -n 's/^  version "\(.*\)"$/\1/p' "$tap_dir/Casks/${member}.rb" 2>/dev/null | head -1)
if [ -n "$existing" ]; then
  newest=$(printf '%s\n%s\n' "$existing" "${VERSION#v}" | sort -V | tail -1)
  if [ "$newest" = "$existing" ] && [ "$existing" != "${VERSION#v}" ]; then
    echo "tap already at ${existing} (newer than ${VERSION#v}); not downgrading"
    exit 0
  fi
fi

cat > "$tap_dir/Casks/${member}.rb" <<CASK
# This file was generated by the ffsstack release workflow. DO NOT EDIT.
cask "${member}" do
  version "${VERSION#v}"

  on_macos do
    on_intel do
      sha256 "${darwin_amd64}"
      url "${base}/${member}_${VERSION}_darwin_amd64.tar.gz",
        verified: "github.com/uinaf/ffsstack/"
    end
    on_arm do
      sha256 "${darwin_arm64}"
      url "${base}/${member}_${VERSION}_darwin_arm64.tar.gz",
        verified: "github.com/uinaf/ffsstack/"
    end
  end

  on_linux do
    on_intel do
      sha256 "${linux_amd64}"
      url "${base}/${member}_${VERSION}_linux_amd64.tar.gz",
        verified: "github.com/uinaf/ffsstack/"
    end
    on_arm do
      sha256 "${linux_arm64}"
      url "${base}/${member}_${VERSION}_linux_arm64.tar.gz",
        verified: "github.com/uinaf/ffsstack/"
    end
  end

${depends_stanza}  binary "${member}"

  homepage "https://github.com/uinaf/ffsstack"
  desc "${description}"
end
CASK

git -C "$tap_dir" add "Casks/${member}.rb"
if git -C "$tap_dir" diff --cached --quiet; then
  echo "cask already current; nothing to publish"
  exit 0
fi
git -C "$tap_dir" -c user.name="$BOT_NAME" -c user.email="$BOT_EMAIL" \
  commit -m "chore(${member}): update to ${VERSION}"
# Both member releases write to the tap; retry on a concurrent push
# instead of failing the release.
for attempt in 1 2 3; do
  if git -C "$tap_dir" push origin HEAD:main; then
    exit 0
  fi
  echo "tap push rejected (attempt ${attempt}); rebasing onto fresh main"
  git -C "$tap_dir" pull --rebase origin main
done
echo "tap push failed after 3 attempts" >&2
exit 1
