#!/usr/bin/env bash
# Render and push the Homebrew cask for one released member.
# Usage: publish-cask.sh <member>  (run from the member directory; expects
# dist/ from goreleaser, TAG, VERSION, GH_TOKEN, BOT_NAME, BOT_EMAIL.)

set -euo pipefail

member=${1:?member name required}
case "$member" in
  slopguard) depends_stanza='  depends_on formula: [
      "git",
      "trufflehog",
    ]
' ;;
  *) depends_stanza='' ;;
esac
[[ "${VERSION:-}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "VERSION missing or invalid" >&2; exit 1; }
[[ "${TAG:-}" == "$member/$VERSION" ]] || { echo "TAG must be $member/VERSION" >&2; exit 1; }

# A retry after publish has no dist/; the published release is the source.
if [ ! -f dist/checksums.txt ]; then
  mkdir -p dist
  gh release download "$TAG" --repo uinaf/ffsstack -p checksums.txt -D dist
fi

sum() {
  awk -v f="${member}_${VERSION}_$1.tar.gz" '$2 == f { print $1 }' dist/checksums.txt
}
darwin_amd64=$(sum darwin_amd64); darwin_arm64=$(sum darwin_arm64)
linux_amd64=$(sum linux_amd64); linux_arm64=$(sum linux_arm64)
for checksum in "$darwin_amd64" "$darwin_arm64" "$linux_amd64" "$linux_arm64"; do
  [[ "$checksum" =~ ^[0-9a-f]{64}$ ]] || { echo "missing archive checksum" >&2; exit 1; }
done

# Release-download URLs URL-encode the slash in the member-prefixed tag.
base="https://github.com/uinaf/ffsstack/releases/download/${member}%2F${VERSION}"
description=$(sed -n 's/^description: *"\{0,1\}\([^"]*\)"\{0,1\}$/\1/p' .goreleaser.yaml | head -1)

tap_dir=$(mktemp -d)
trap 'rm -rf "$tap_dir"' EXIT
git clone --depth 1 "https://x-access-token:${GH_TOKEN}@github.com/uinaf/homebrew-tap.git" "$tap_dir"

cat > "$tap_dir/Casks/${member}.rb" <<CASK
# This file was generated by the ffsstack release workflow. DO NOT EDIT.
cask "${member}" do
  version "${VERSION#v}"

  on_macos do
    on_intel do
      sha256 "${darwin_amd64}"
      url "${base}/${member}_${VERSION}_darwin_amd64.tar.gz",
        verified: "github.com/uinaf/ffsstack/"
    end
    on_arm do
      sha256 "${darwin_arm64}"
      url "${base}/${member}_${VERSION}_darwin_arm64.tar.gz",
        verified: "github.com/uinaf/ffsstack/"
    end
  end

  on_linux do
    on_intel do
      sha256 "${linux_amd64}"
      url "${base}/${member}_${VERSION}_linux_amd64.tar.gz",
        verified: "github.com/uinaf/ffsstack/"
    end
    on_arm do
      sha256 "${linux_arm64}"
      url "${base}/${member}_${VERSION}_linux_arm64.tar.gz",
        verified: "github.com/uinaf/ffsstack/"
    end
  end

${depends_stanza}  binary "${member}"

  homepage "https://github.com/uinaf/ffsstack"
  desc "${description:-$member}"
end
CASK

git -C "$tap_dir" add "Casks/${member}.rb"
if git -C "$tap_dir" diff --cached --quiet; then
  echo "cask already current; nothing to publish"
  exit 0
fi
git -C "$tap_dir" -c user.name="$BOT_NAME" -c user.email="$BOT_EMAIL" \
  commit -m "chore(${member}): update to ${VERSION}"
git -C "$tap_dir" push origin HEAD:main
