#!/usr/bin/env bash
# Render and publish the Homebrew cask for one released member.
# Usage: publish-cask.sh <member>  (run from the member directory; expects
# dist/ from goreleaser, TAG, VERSION, GH_TOKEN.)

set -euo pipefail

member=${1:?member name required}
case "$member" in
  slopguard) depends_stanza='  depends_on formula: [
      "git",
      "trufflehog",
    ]
' ;;
  *) depends_stanza='' ;;
esac
[[ "${VERSION:-}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "VERSION missing or invalid" >&2; exit 1; }
[[ "${TAG:-}" == "$member/$VERSION" ]] || { echo "TAG must be $member/VERSION" >&2; exit 1; }

# A retry after publish has no dist/; the published release is the source.
if [ ! -f dist/checksums.txt ]; then
  mkdir -p dist
  gh release download "$TAG" --repo uinaf/ffss -p checksums.txt -D dist
fi

sum() {
  awk -v f="${member}_${VERSION}_$1.tar.gz" '$2 == f { print $1 }' dist/checksums.txt
}
darwin_amd64=$(sum darwin_amd64); darwin_arm64=$(sum darwin_arm64)
linux_amd64=$(sum linux_amd64); linux_arm64=$(sum linux_arm64)
for checksum in "$darwin_amd64" "$darwin_arm64" "$linux_amd64" "$linux_arm64"; do
  [[ "$checksum" =~ ^[0-9a-f]{64}$ ]] || { echo "missing archive checksum" >&2; exit 1; }
done

# Release-download URLs URL-encode the slash in the member-prefixed tag.
# Ruby #{version} interpolation keeps `brew audit` treating the URL as versioned.
base='https://github.com/uinaf/ffss/releases/download/'"${member}"'%2Fv#{version}'
case "$member" in
  slopmachine) description="Deterministic and structured approach to slop cannoning" ;;
  slopguard) description="Structured independent code review as a CLI and agent skill" ;;
  *) description="$member" ;;
esac

# The tap's default branch requires signed commits, so the cask is written
# through the contents API — GitHub signs API commits, and the sha
# parameter makes each write a compare-and-swap.
cask_path="Casks/${member}.rb"
rendered=$(mktemp)
trap 'rm -f "$rendered"' EXIT

cat > "$rendered" <<CASK
# This file was generated by the ffss release workflow. DO NOT EDIT.
cask "${member}" do
  version "${VERSION#v}"

  on_macos do
    on_intel do
      sha256 "${darwin_amd64}"
      url "${base}/${member}_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/uinaf/ffss/"
    end
    on_arm do
      sha256 "${darwin_arm64}"
      url "${base}/${member}_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/uinaf/ffss/"
    end
  end

  on_linux do
    on_intel do
      sha256 "${linux_amd64}"
      url "${base}/${member}_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/uinaf/ffss/"
    end
    on_arm do
      sha256 "${linux_arm64}"
      url "${base}/${member}_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/uinaf/ffss/"
    end
  end

  livecheck do
    url :homepage
    regex(%r{${member}/v?(\d+(?:\.\d+)+)}i)
    strategy :github_releases
  end

${depends_stanza}  name "${member}"

  binary "${member}"

  homepage "https://github.com/uinaf/ffss"
  desc "${description}"
end
CASK

content_b64=$(base64 < "$rendered" | tr -d '\n')

# Both member releases write to the tap; a stale sha means a concurrent
# write, so refetch and retry instead of failing the release.
for attempt in 1 2 3; do
  existing_sha=
  existing_version=
  if existing=$(gh api "repos/uinaf/homebrew-tap/contents/${cask_path}" 2>/dev/null); then
    existing_sha=$(jq -r .sha <<<"$existing")
    existing_content=$(jq -r '.content | gsub("\n"; "") | @base64d' <<<"$existing")
    if [ "$existing_content" = "$(cat "$rendered")" ]; then
      echo "cask already current; nothing to publish"
      exit 0
    fi
    existing_version=$(sed -n 's/^  version "\(.*\)"$/\1/p' <<<"$existing_content" | head -1)
  fi
  # Rerunning an old workflow must never downgrade the tap.
  if [ -n "$existing_version" ]; then
    newest=$(printf '%s\n%s\n' "$existing_version" "${VERSION#v}" | sort -V | tail -1)
    if [ "$newest" = "$existing_version" ] && [ "$existing_version" != "${VERSION#v}" ]; then
      echo "tap already at ${existing_version} (newer than ${VERSION#v}); not downgrading"
      exit 0
    fi
  fi
  if gh api -X PUT "repos/uinaf/homebrew-tap/contents/${cask_path}" \
      -f message="chore(${member}): update to ${VERSION}" \
      -f content="$content_b64" \
      ${existing_sha:+-f sha="$existing_sha"} >/dev/null; then
    echo "cask published"
    exit 0
  fi
  echo "tap write conflicted (attempt ${attempt}); retrying"
done
echo "tap write failed after 3 attempts" >&2
exit 1
